import Player from "../../assets/image/player.svg";
import Player1 from "../../assets/image/player1.svg";
import Player2 from "../../assets/image/player2.svg";
import Player3 from "../../assets/image/player3.svg";
import Player4 from "../../assets/image/player4.svg";
import Player5 from "../../assets/image/player5.svg";

export const PlayerInformation = [
  {
    id: "101",
    image: Player1,
    name: "Steven Adams",
    position: "Center",
    pointsPerGame: "8.6",
    assistsPerGame: "2.3",
    reboundPerGame: "11.2",
  },
  {
    id: "102",
    image: Player2,
    name: "Bam Adebayo",
    position: "Center-Forward",
    pointsPerGame: "19.3",
    assistsPerGame: "3.9",
    reboundPerGame: "10.4",
  },
  {
    id: "103",
    image: Player3,
    name: "Ocahi Agbaji",
    position: "Guard",
    pointsPerGame: "5.8",
    assistsPerGame: "1.1",
    reboundPerGame: "2.8",
  },
  {
    id: "104",
    image: Player4,
    name: "Santi Aldama",
    position: "Forward-Center",
    pointsPerGame: "10.7",
    assistsPerGame: "2.3",
    reboundPerGame: "5.8",
  },

  {
    id: "10524",
    image: Player,
    name: "Precious Achiuwa",
    position: "Forward",
    pointsPerGame: "7.6",
    assistsPerGame: "1.3",
    reboundPerGame: "6.6",
  },
  {
    id: "1024",
    image: Player1,
    name: "Steven Adams",
    position: "Center",
    pointsPerGame: "8.6",
    assistsPerGame: "2.3",
    reboundPerGame: "11.2",
  },
  {
    id: "10345",
    image: Player2,
    name: "Bam Adebayo",
    position: "Center-Forward",
    pointsPerGame: "19.3",
    assistsPerGame: "3.9",
    reboundPerGame: "10.4",
  },
  {
    id: "166",
    image: Player3,
    name: "Ocahi Agbaji",
    position: "Guard",
    pointsPerGame: "5.8",
    assistsPerGame: "1.1",
    reboundPerGame: "2.8",
  },
  {
    id: "1512",
    image: Player4,
    name: "Santi Aldama",
    position: "Forward-Center",
    pointsPerGame: "10.7",
    assistsPerGame: "2.3",
    reboundPerGame: "5.8",
  },
  {
    id: "140",
    image: Player,
    name: "Precious Achiuwa",
    position: "Forward",
    pointsPerGame: "7.6",
    assistsPerGame: "1.3",
    reboundPerGame: "6.6",
  },
  {
    id: "1231",
    image: Player1,
    name: "Steven Adams",
    position: "Center",
    pointsPerGame: "8.6",
    assistsPerGame: "2.3",
    reboundPerGame: "11.2",
  },
  {
    id: "1043",
    image: Player2,
    name: "Bam Adebayo",
    position: "Center-Forward",
    pointsPerGame: "19.3",
    assistsPerGame: "3.9",
    reboundPerGame: "10.4",
  },
  {
    id: "1433",
    image: Player3,
    name: "Ocahi Agbaji",
    position: "Guard",
    pointsPerGame: "5.8",
    assistsPerGame: "1.1",
    reboundPerGame: "2.8",
  },
  {
    id: "16234",
    image: Player4,
    name: "Santi Aldama",
    position: "Forward-Center",
    pointsPerGame: "10.7",
    assistsPerGame: "2.3",
    reboundPerGame: "5.8",
  },
  {
    id: "1533",
    image: Player3,
    name: "Ocahi Agbaji",
    position: "Guard",
    pointsPerGame: "5.8",
    assistsPerGame: "1.1",
    reboundPerGame: "2.8",
  },
];
